with open('compiler.c', 'w') as f:
	f.write('''#include "compiler.h"

/* This file is generated by gencompilerc.py.
 * Do not edit by hand.
 * Also, this file is automatically updated
 * by make when the project is built.
 */

V load_compiler(V global)
{
	char compiler[] = {''')
	with open('compiler.vu', 'rb') as std:
		for n, char in enumerate(std.read()):
			if n % 8 == 0:
				f.write("\n		")
			f.write(r"'\x%02x', " % ord(char))
	f.write('''
	};
	return load_memfile(compiler, sizeof compiler, a_to_string("(compiler)"), global);
}
''')
